FROM "pandoc/latex:latest-ubuntu"

# RUN apk --update --no-cache add make msttcorefonts-installer fontconfig && \
#     update-ms-fonts && \
#     fc-cache -f && \
#     tlmgr update --self --all && \
#     tlmgr install collection-langjapanese
